<?php

  /**
   * @file
   * Contains dsu_c_sideimagetext.module.
   */

  /**
   * Implements hook_preprocess_HOOK() for paragraph.html.twig.
   */
  function dsu_c_sideimagetext_preprocess_paragraph(&$variables) {
    // Load the css file when the rendered element is a Text Paragraph.
    $variables['#attached']['library'][] = 'dsu_c_sideimagetext/general';
    if ($variables['paragraph']->getType() == 'c_sideimagetext') {
      if (isset( $variables['content']['field_background_image'] )) {
        $ref_entities_classy_para = $variables['paragraph']->get( 'field_classy_paragraph_style' )
          ->referencedEntities();
        if (!empty( $ref_entities_classy_para )) {
          $ref_entity_classy_para = array_shift( $ref_entities_classy_para );
          if (!empty( $ref_entity_classy_para )) {
            $classy_paragraph = $ref_entity_classy_para->id();
            if ($classy_paragraph == 'dsu_classy_text_image_background') {
              if (isset( $variables['content']['field_background_image']['#items'] )) {
                $ref_entities = $variables['content']['field_background_image']['#items']->referencedEntities();
                $ref_entity = array_shift( $ref_entities );
                $fid = $ref_entity->get( 'image' )
                  ->first()
                  ->getValue()['target_id'];
                $file = \Drupal\file\Entity\File::load( $fid );
                $url = \Drupal\image\Entity\ImageStyle::load( 'text_background_image_1920x795_' )
                  ->buildUrl( $file->getFileUri() );
                $variables['field_background_image_img_url'] = $url;
              }
            }
          }
        }
      }
    }
  }

  /**
   * Implements hook_theme.
   */
  function dsu_c_sideimagetext_theme($existing, $type, $theme, $path) {
    return [
      'paragraph__c_sideimagetext' => [
        'template' => 'paragraph--c-sideimagetext',
        'base hook' => 'paragraphs',
      ],
    ];
  }
