<?php

/**
 * @file
 * Contains ln_c_webform.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ln_c_webform_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ln_c_webform module.
    case 'help.page.ln_c_webform':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides webform as a paragraph.') . '</p>';
      return $output;

    default:
  }
}
