<?php

/**
 * Implements HOOK_preprocess_theme().
 */
function dsu_c_externalvideo_theme($existing, $type, $theme, $path) {
    return [
    'paragraph__c_externalvideo' => [
      'template' => 'paragraph--c-externalvideo',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_externalvideo_preprocess_paragraph(&$variables) {
  if($variables['paragraph']->getType() == 'c_externalvideo') {
    $variables['#attached']['library'][] = 'dsu_c_externalvideo/external-video';
  }
}

