<?php

  use Drupal\file\Entity\File;
  use Drupal\media\Entity\Media;

  /**
   * Implements HOOK_preprocess_theme().
   */
  function dsu_c_gallery_theme($existing, $type, $theme, $path) {
    return [
      'paragraph__c_gallery_item' => [
        'template' => 'paragraph--c-gallery-item',
        'base hook' => 'paragraphs',
      ],
      'paragraph__c_gallery' => [
        'template' => 'paragraph--c-gallery',
        'base hook' => 'paragraphs',
      ],
      'paragraph__dsu_gallery' => [
        'template' => 'paragraph--dsu-gallery',
        'variables' => [
          'gallery' => NULL,
          'gallery_preview' => NULL,
          'parent_paragraph' => NULL,
        ],
      ],
    ];
  }

  /**
   * Implements hook_preprocess_HOOK() for paragraph.html.twig.
   */
  function dsu_c_gallery_preprocess_paragraph(&$variables) {
    $slick_responsive = TRUE;

    if ($slick_responsive == TRUE) {
      if ($variables['paragraph']->getType() == 'c_gallery') {
        $slick = \Drupal::service( 'slick.manager' );
        $build = [];
        $build['settings'] = [
          'optionset' => 'gallery_slick',
        ];
        $paragraph_view_builder = \Drupal::entityManager()
          ->getViewBuilder( 'paragraph' );
        $gallery_item_entity_display_settings = entity_get_display( 'paragraph', 'c_gallery_item', 'default' );
        $item_ids = [];
        foreach ($variables['paragraph']->get( 'field_c_gallery_item' )
                   ->getValue() as $item) {
          $item_ids[] = $item['target_id'];
        }
        $gallery_items = \Drupal::entityManager()
          ->getStorage( 'paragraph' )
          ->loadMultiple( $item_ids );
        $gallery = [];
        if (!empty( $gallery_items )) {
          $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
          foreach ($gallery_items as $gallery_item) {
            if ($gallery_item->hasTranslation( $language )) {
              $item_translation = $gallery_item->getTranslation( $language );
              $gallery[$gallery_item->id()] = [];
              $gallery_field = '';
              if (!empty( $item_translation->get( 'field_c_title' )
                ->getValue() )) {
                $gallery[$gallery_item->id()]['field_c_title'] = $item_translation->get( 'field_c_title' )
                  ->getString();
              }
              if (!empty( $item_translation->get( 'field_title_positions' )
                ->getValue() )) {
                $gallery[$gallery_item->id()]['field_title_positions'] = $item_translation->get( 'field_title_positions' )
                  ->getString();
              }
              if (!empty( $gallery_item->get( 'field_c_thumbnail_image' )
                ->getValue() )) {
                $gallery[$gallery_item->id()]['field_c_thumbnail_image'] = $paragraph_view_builder->viewField( $gallery_item->field_c_thumbnail_image, $gallery_item_entity_display_settings->getComponent( 'field_c_thumbnail_image' ) );
                if (!empty( $gallery_item->get( 'field_c_thumbnail_image' )
                  ->first() )) {
                  $image_id = $gallery_item->get( 'field_c_thumbnail_image' )
                    ->getString();
                  $image_data = get_dsu_gallery_image_url( $image_id );
                  $gallery[$gallery_item->id()]['thumbnail_url'] = $image_data['url'];
                }
              }
              if (!empty( $gallery_item->get( 'field_c_image' )->getValue() )) {
                $gallery_field = 'field_c_image';
                if (!empty( $gallery_item->get( 'field_c_image' )->first() )) {
                  $image_id = $gallery_item->get( 'field_c_image' )
                    ->getString();
                  $image_data = get_dsu_gallery_image_url( $image_id );
                  $gallery[$gallery_item->id()]['image_url'] = $image_data['url'];
                  $gallery[$gallery_item->id()]['video_url'] = '';
                }
              }
              if (!empty( $gallery_item->get( 'field_c_gallery_video_embed_url' )
                ->getValue() )) {
                $gallery_field = 'field_c_gallery_video_embed_url';
                $gallery[$gallery_item->id()]['video_url'] = $gallery_item->get( 'field_c_gallery_video_embed_url' )
                  ->getString();
              }
              if ($gallery_field != '') {
                $gallery[$gallery_item->id()][$gallery_field] = $paragraph_view_builder->viewField( $gallery_item->$gallery_field, $gallery_item_entity_display_settings->getComponent( $gallery_field ) );
              }
            }
          }
        }
        if (!empty( $gallery )) {
          $variables['content']['field_c_gallery_item'] = [
            '#theme' => 'paragraph__dsu_gallery',
            '#gallery' => $gallery,
            '#gallery_preview' => NULL,
            '#parent_paragraph' => NULL,
          ];
          $variables['#attached']['library'][] = 'dsu_c_gallery/gallery';
          if (array_key_exists( '#attached', $variables )) {
            if (in_array( 'dsu_c_gallery/dsu-gallery', $variables['#attached']['library'] )) {
              $key = array_search( 'dsu_c_gallery/dsu-gallery', $variables['#attached']['library'] );
              unset( $variables['#attached']['library'][$key] );
              $variables['#attached']['library'] = array_values( $variables['#attached']['library'] );
            }
          }
        }
      }
    }
    else {
      if ($variables['paragraph']->getType() === 'c_gallery') {
        $variables['#attached']['library'][] = 'dsu_c_gallery/gallery';
        $variables['attributes']['id'] = 'dsu-gallery-content--' . $variables['paragraph']->id();
        $variables['attributes']['class'][] = 'dsu-gallery-content';
      }
      elseif ($variables['paragraph']->getType() === 'c_gallery_item') {
        $variables['#attached']['library'][] = 'dsu_c_gallery/gallery-item';

        if (isset( $variables['content']['field_c_gallery_video_embed_url']['#theme'] )
          && isset( $variables['content']['field_c_image']['#theme'] )) {
          unset( $variables['content']['field_c_image'] );
        }
      }
    }
  }

  /**
   * Implements hook_preprocess_hook() for field.html.twig.
   */
  function dsu_c_gallery_preprocess_field(&$variables) {
    if ($variables['entity_type'] === 'paragraph' && $variables['element']['#object']->getType() == 'c_gallery') {
      if (!empty( $variables['items'] )) {
        foreach ($variables['items'] as $key => $value) {
          $variables['items'][$key]['attributes']->setAttribute( 'class', 'dsu-gallery-content--items' );
        }
      }
    }
    if ($variables['entity_type'] === 'paragraph' && $variables['element']['#object']->getType() == 'c_gallery_item') {
      if ($variables['field_name'] === 'field_c_image' || $variables['field_name'] === 'field_c_gallery_video_embed_url') {
        $variables['attributes']['id'] = 'dsu-gallery-content--item-' . $variables['element']['#object']->id();
        $variables['attributes']['class'][] = 'dsu-gallery-content--item';
      }
      elseif ($variables['field_name'] === 'field_c_thumbnail_image') {
        $variables['attributes']['id'] = 'dsu-gallery-content--preview-' . $variables['element']['#object']->id();
        $variables['attributes']['target-gallery'] = 'dsu-gallery-content--preview-' . $variables['element']['#object']->id();
        $variables['attributes']['class'][] = 'dsu-gallery-content--preview';
      }
    }
  }

  /**
   * Get image file url.
   */
  function get_dsu_gallery_image_url($image_id) {
    $return_date = [];
    $entity_image = Media::load( $image_id );
    if (!empty( $entity_image ) && !empty( $entity_image->get( 'image' )
        ->first() )) {
      $image_file_id = $entity_image->get( 'image' )
        ->first()
        ->get( 'target_id' )
        ->getString();
      $image_file_id = File::load( $image_file_id );
      $image_file_alt_text = $entity_image->get( 'image' )
        ->first()
        ->get( 'alt' )
        ->getString();
      $return_date['url'] = file_create_url( $image_file_id->getFileUri() );
      $return_date['alt'] = $image_file_alt_text;
    }

    return $return_date;
  }
