<?php

use Drupal\bootstrap\Bootstrap;
use Drupal\bootstrap\Utility\Element;

/**
 * Implements HOOK_preprocess_theme().
 */
function dsu_c_link_document_container_theme($existing, $type, $theme, $path) {
    return [
    'paragraph__c_link_document_container' => [
      'template' => 'paragraph--c-link-document-container',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_link' => [
      'template' => 'paragraph--c-link',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_document' => [
      'template' => 'paragraph--c-document',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_link_document_container_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'c_document' || $variables['paragraph']->getType() == 'c_link') {
    $variables['#attached']['library'][] = 'dsu_c_link_document_container/link-container';
  }
}